/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SasGyula(SZOFT_2023_
 */
public class halallabirintus extends javax.swing.JFrame {

    /**
     * Creates new form labirintus1
     */
    public halallabirintus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSura = new javax.swing.JLabel();
        lblWari = new javax.swing.JLabel();
        btnSura = new javax.swing.JButton();
        btnWari = new javax.swing.JButton();
        lblHatter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/sura.png"))); // NOI18N
        getContentPane().add(lblSura, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 230, -1));

        lblWari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/wari.png"))); // NOI18N
        getContentPane().add(lblWari, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 19, 230, -1));

        btnSura.setText("Sura");
        btnSura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuraActionPerformed(evt);
            }
        });
        getContentPane().add(btnSura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        btnWari.setText("Harcos");
        btnWari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWariActionPerformed(evt);
            }
        });
        getContentPane().add(btnWari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/hatter2.jpg"))); // NOI18N
        getContentPane().add(lblHatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(rootPane, "Egy versenyre nevezel, aminek a lényege,\n hogy át kell kelni a halállabirintuson.\n A labirintusban tárgyakat találhatsz és \n szörnyekkel kell harcoljál. \n Válassz karaktert!");
    }//GEN-LAST:event_formWindowOpened

    private void btnSuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuraActionPerformed
    JFrame jatek = new jatek();
    jatek.show();
    
    dispose();
    }//GEN-LAST:event_btnSuraActionPerformed

    private void btnWariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWariActionPerformed
    JFrame jatek2 = new jatek2();
    jatek2.show();
    
    dispose();
    }//GEN-LAST:event_btnWariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halallabirintus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSura;
    private javax.swing.JButton btnWari;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblSura;
    private javax.swing.JLabel lblWari;
    // End of variables declaration//GEN-END:variables
}
