/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SasGyula(SZOFT_2023_
 */
public class harc2 extends javax.swing.JFrame {
        int oriasEletero =  0;
        int oriasUgyesseg = 0;
        int oriasSzerencse = 0;
        int karakterEletero = 0;
        int karakterUgyesseg = 0;
        int karakterSzerencse = 0;
        int tamadas = 0;
        int visszavag = 0;
        double eletero = 0;
        double ugyesseg = 0;
        double szerencse = 0;
    /**
     * Creates new form harc
     */
    public harc2() {
        initComponents();
        btnTamadas.setVisible(false);
        pbOriasEletero.setValue(70);
        pbOriasUgyesseg.setValue(70);
        pbOriasSzerencse.setValue(40);


    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnTamadas = new javax.swing.JButton();
        btnDobokocka = new javax.swing.JButton();
        lblOrias = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pbKarakterEletero = new javax.swing.JProgressBar();
        pbKarakterUgyesseg = new javax.swing.JProgressBar();
        pbKarakterSzerencse = new javax.swing.JProgressBar();
        lblSzerencse = new javax.swing.JLabel();
        lblUgyesseg = new javax.swing.JLabel();
        lblEletero = new javax.swing.JLabel();
        pbOriasEletero = new javax.swing.JProgressBar();
        pbOriasUgyesseg = new javax.swing.JProgressBar();
        pbOriasSzerencse = new javax.swing.JProgressBar();
        lblOSzerencse = new javax.swing.JLabel();
        lblOUgyesseg = new javax.swing.JLabel();
        lblOEletero = new javax.swing.JLabel();
        lblHarcos = new javax.swing.JLabel();
        lblBOrias = new javax.swing.JLabel();
        lblHatter = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTamadas.setText("Támadás");
        btnTamadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamadasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTamadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 247, -1, -1));

        btnDobokocka.setText("Dobókocka");
        btnDobokocka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDobokockaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDobokocka, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 247, -1, -1));

        lblOrias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/orias.png"))); // NOI18N
        getContentPane().add(lblOrias, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 6, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/wariHarc.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 129, -1, 112));
        getContentPane().add(pbKarakterEletero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 116, 16));
        getContentPane().add(pbKarakterUgyesseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 116, 16));
        getContentPane().add(pbKarakterSzerencse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 116, 16));

        lblSzerencse.setForeground(new java.awt.Color(255, 255, 255));
        lblSzerencse.setText("Szerencse");
        getContentPane().add(lblSzerencse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblUgyesseg.setForeground(new java.awt.Color(255, 255, 255));
        lblUgyesseg.setText("Ügyesség");
        getContentPane().add(lblUgyesseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lblEletero.setForeground(new java.awt.Color(255, 255, 255));
        lblEletero.setText("Életerő");
        lblEletero.setToolTipText("");
        getContentPane().add(lblEletero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(pbOriasEletero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 124, 16));
        getContentPane().add(pbOriasUgyesseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 124, 16));
        getContentPane().add(pbOriasSzerencse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 124, 16));

        lblOSzerencse.setForeground(new java.awt.Color(255, 255, 255));
        lblOSzerencse.setText("Szerencse");
        getContentPane().add(lblOSzerencse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lblOUgyesseg.setForeground(new java.awt.Color(255, 255, 255));
        lblOUgyesseg.setText("Ügyesség");
        getContentPane().add(lblOUgyesseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        lblOEletero.setForeground(new java.awt.Color(255, 255, 255));
        lblOEletero.setText("Életerő");
        getContentPane().add(lblOEletero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblHarcos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHarcos.setForeground(new java.awt.Color(255, 255, 255));
        lblHarcos.setText("Harcos");
        getContentPane().add(lblHarcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lblBOrias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBOrias.setForeground(new java.awt.Color(255, 255, 255));
        lblBOrias.setText("Barlangi Óriás");
        getContentPane().add(lblBOrias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/halallabirintus/hatter5.png"))); // NOI18N
        getContentPane().add(lblHatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTamadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamadasActionPerformed
    harcmenet();
    nyertel();
    }//GEN-LAST:event_btnTamadasActionPerformed

    private void btnDobokockaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDobokockaActionPerformed
        dobokocka();
    }//GEN-LAST:event_btnDobokockaActionPerformed

    private void dobokocka() {
        eletero = Math.random() * 101;
        szerencse = Math.random() * 41;
        ugyesseg = Math.random() * 101;
        pbKarakterEletero.setValue((int) eletero + (int) szerencse);
        pbKarakterUgyesseg.setValue((int) ugyesseg + (int) szerencse);
        pbKarakterSzerencse.setValue((int) szerencse);
        btnDobokocka.setVisible(false);
        btnTamadas.setVisible(true);
    }

    private void harcmenet() {
        oriasEletero = pbOriasEletero.getValue();
        karakterUgyesseg = pbKarakterUgyesseg.getValue();
        oriasUgyesseg = pbOriasUgyesseg.getValue();
        karakterEletero = pbKarakterEletero.getValue();
        
        
        tamadas = oriasEletero - karakterEletero;
        visszavag = karakterEletero - oriasUgyesseg;
        
        if(tamadas < 0){
            pbOriasEletero.setValue(tamadas);
        }else if(visszavag < 0){
            pbKarakterEletero.setValue(visszavag);
        }
    }
    private void nyertel() throws HeadlessException {
        if (pbKarakterEletero.getValue() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Vesztettél, próbáld újra!");
            JFrame harc = new harc2();
            harc.show();
            
            dispose();
            
        } else if (pbOriasEletero.getValue() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nyertél");
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(harc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(harc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(harc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(harc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new harc2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDobokocka;
    private javax.swing.JButton btnTamadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBOrias;
    private javax.swing.JLabel lblEletero;
    private javax.swing.JLabel lblHarcos;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblOEletero;
    private javax.swing.JLabel lblOSzerencse;
    private javax.swing.JLabel lblOUgyesseg;
    private javax.swing.JLabel lblOrias;
    private javax.swing.JLabel lblSzerencse;
    private javax.swing.JLabel lblUgyesseg;
    private javax.swing.JProgressBar pbKarakterEletero;
    private javax.swing.JProgressBar pbKarakterSzerencse;
    private javax.swing.JProgressBar pbKarakterUgyesseg;
    private javax.swing.JProgressBar pbOriasEletero;
    private javax.swing.JProgressBar pbOriasSzerencse;
    private javax.swing.JProgressBar pbOriasUgyesseg;
    // End of variables declaration//GEN-END:variables
}
